### ISSUE TITLE
Unable to build on macos 26.0.1

### ISSUE THREAD

**Issue by blackrez** [FoundationDB/fdb-swift-bindings#14]
Hello, 

I tried to use the binding on the latest version of macos but I got this error : 

```
/Users/nabil/projects/gnop/app-swift/front/.build/checkouts/fdb-swift-bindings/Sources/CFoundationDB/fdb_c_wrapper.h:25:10: error: 'foundationdb/fdb_c.h' file not found
23 |
24 | #define FDB_API_VERSION FDB_LATEST_API_VERSION
25 | #include <foundationdb/fdb_c.h>
   |          `- error: 'foundationdb/fdb_c.h' file not found
26 |
27 | #endif
```

The libs are installed : 

```
➜  ~ ls /usr/local/include/foundationdb
fdb_c_apiversion.g.h fdb_c_internal.h     fdb_c_options.g.h    fdb_c_types.h        fdb_c.h              fdb.options
```

I also tried to make a configuration file for pkg-config but I think it wasn't correct.

**Comment by blackrez** [comment]
I find the issue. 

I used the pkg-config file include in `Sources/CFoundationDB/include` and fix the Cflags parts (there was a typo). Now I get this :

```
prefix=/usr/local
exec_prefix=${prefix}
includedir=${prefix}/include
libdir=${exec_prefix}/lib

Name: CFoundationDB
Description: The foundationdb C library
Version: 7.3.9
Cflags: -I${includedir}
Libs: -L${libdir} -lfdb_c
```

**Comment by vishesh** [comment]
Did that fix the issue? How did you install client libraries?

**Comment by blackrez** [comment]
> Did that fix the issue? How did you install client libraries?

Yes, I make a PR about installations.

**Comment by vishesh** [comment]
Thank you. Merged the PR.
